version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ruang_user
      POSTGRES_PASSWORD: ruang_password
      POSTGRES_DB: ruang_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DB_URL: postgres://ruang_user:ruang_password@postgres:5432/ruang_db
      REDIS_URL: redis://redis:6379
      PINATA_JWT: ${PINATA_JWT}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: